# Site settings
title: ASD
header-img: img/home-bg.png
email: a.s.diaz8@gmail.com
copyright_name: alxclmb
description: > # this means to ignore newlines until "baseurl:"
  Reciprocal Rabble
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alxclmb
learn_profile: alxclmb
email_username: a.s.diaz8@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
